db:
  enginename: ""
  username: ""
  password: ""
  host: ""
  port: ""
  dbname: ""
  charset: ""

redis:
  password: ""
  host: ""
  port: ""

secret:
  privatekey: ""
  publickey: ""
  tokenKey: ""